---

- name: install packagecloud dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - ca-certificates
    - pygpgme
    - yum-utils

- name: add packagecloud repository
  template:
    src: templates/escapace_stack.repo.j2
    dest: "/etc/yum.repos.d/escapace_stack.repo"
    mode: 0644
    owner: root
    group: root
  register: packagecloud_repository

- name: retrieving packagecloud gpg keys
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - 'https://packagecloud.io/gpg.key'
    - 'https://packagecloud.io/escapace/stack/gpgkey'
    - 'https://escapace.github.io/security/GPG-KEY-ESCAPACE'
  when: packagecloud_repository | changed

- name: yum makecache
  shell: yum -q -y makecache fast warn=no
  when: packagecloud_repository | changed
