---

- name: install packagecloud dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items:
    - ca-certificates
    - pygpgme
    - yum-utils

- name: retrieving packagecloud gpg key
  rpm_key: state=present key=https://packagecloud.io/gpg.key

- name: retrieving packaging@epiloque.com gpg key
  rpm_key: state=present key=https://epiloque.github.io/packaging.pub

- name: add packagecloud repository
  template:
    src: templates/epiloque_ec.repo.j2
    dest: "/etc/yum.repos.d/epiloque_ec.repo"
    mode: 0644
    owner: root
    group: root
  register: packagecloud_ec_repository

- name: yum makecache
  shell: yum -q -y makecache fast warn=no
  when: packagecloud_ec_repository | changed
