---


- name: install packages
  package:
    name: ["ca-certificates", "python3-gpg", "yum-utils"]
    state: present

- name: add packagecloud repository
  template:
    src: templates/escapace_stack.repo.j2
    dest: "/etc/yum.repos.d/escapace_stack.repo"
    mode: 0644
    owner: root
    group: root
  register: packagecloud_repository

- name: retrieving packagecloud gpg keys
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - 'https://packagecloud.io/escapace/stack/gpgkey'
    - 'https://escapace.github.io/security/GPG-KEY-ESCAPACE'
