---
- name: Converge
  hosts: all
  roles:
    - role: escapace.packagecloud
  tasks:
    - name: install an rpm from the packagecloud repo
      yum:
        name: ferm
        state: present
        update_cache: yes
