---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
lint: |
    yamllint .
    ansible-lint .
platforms:
  - name: instance
    image: escapace/test-centos:8
provisioner:
  name: ansible
